"""categories

Revision ID: a4531730c143
Revises: 7b6cb1ade18f
Create Date: 2026-04-24 15:27:02.440397

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4531730c143'
down_revision: Union[str, Sequence[str], None] = '7b6cb1ade18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('ux_categories_default_lower_name', 'categories', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('ux_categories_user_lower_name', 'categories', ['user_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))

    from app.db.seed import DEFAULT_CATEGORIES
    categories_table = sa.table(
        "categories",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("is_default", sa.Boolean()),
        sa.column("user_id", sa.Uuid()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "id": uuid.uuid4(),
                "name": name,
                "is_default": True,
                "user_id": None,
                "created_at": datetime.now(timezone.utc),
            }
            for name in DEFAULT_CATEGORIES
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_categories_user_lower_name', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ux_categories_default_lower_name', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
